kind: pipeline
name: "Test master push"

concurrency:
  limit: 2

steps:
  - name: "Verify & build"
    image: node
    environment:
      NEXT_PUBLIC_SUPABASE_URL:
        from_secret: NEXT_PUBLIC_SUPABASE_URL
      NEXT_PUBLIC_SUPABASE_ANON_KEY:
        from_secret: NEXT_PUBLIC_SUPABASE_ANON_KEY
    commands:
      - npm install
      - npm run build
  - name: "Build docker image"
    image: plugins/docker
    settings:
      repo: mytsv/supabase-hackademy
      tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password 

trigger:
  branch:
  - main
  # branch:
  #   exclude:
  #   - main
  event:
  - pull_request
  - push