kind: pipeline
name: "Test master push"

concurrency:
  limit: 2

steps:
  - name: "Verify & build"
    image: node
    environment:
      NEXT_PUBLIC_SUPABASE_URL:
        from_secret: NEXT_PUBLIC_SUPABASE_URL
      NEXT_PUBLIC_SUPABASE_ANON_KEY:
        from_secret: NEXT_PUBLIC_SUPABASE_ANON_KEY
    commands:
      - npm install
      - npm run build
  - name: "Build docker image"
    image: plugins/docker
    commands:
      - sudo docker build -t mytsv/supabase-hackademy-private:${DRONE_COMMIT_SHA:0:7} .
      - sudo docker push mytsv/supabase-hackademy-private:${DRONE_COMMIT_SHA:0:7}   

trigger:
  branch:
  - main
  # branch:
  #   exclude:
  #   - main
  event:
  - pull_request
  - push